runtime: python27
api_version: 1
threadsafe: true

skip_files:
- e2e/
- node_modules/
- src/
- .editorconfig
- .gitignore
- angular.json
- package-lock.json
- package.json
- README.md
- tsconfig.json
- tslint.json

handlers:

- url: /(.*\.(gif|png|jpg|css|js|ico)(|\.map))$
  static_files: dist/abumahlad/\1
  upload: dist/abumahlad/(.*)(|\.map)

- url: /(.*)
  static_files: dist/abumahlad/index.html
  upload: dist/abumahlad/index.html
